# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile.rb, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{frbr}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ross Singer"]
  s.date = %q{2010-09-20}
  s.description = %q{A set of modules for creating simple FRBR (Functional Requirements for Bibliographic Resources) relationships between objects.  Includes Group 1, 2 and 3 entities.}
  s.email = %q{rossfsinger@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "lib/frbr.rb",
     "lib/frbr/concept.rb",
     "lib/frbr/corporate_body.rb",
     "lib/frbr/event.rb",
     "lib/frbr/expression.rb",
     "lib/frbr/family.rb",
     "lib/frbr/groups.rb",
     "lib/frbr/item.rb",
     "lib/frbr/manifestation.rb",
     "lib/frbr/object.rb",
     "lib/frbr/person.rb",
     "lib/frbr/place.rb",
     "lib/frbr/work.rb"
  ]
  s.homepage = %q{http://github.com/rsinger/ruby-frbr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A set of modules for creating simple FRBR relationships between objects.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

